export const NAV_ITEMS = [
  { href: "/", label: "Dashboard", icon: "LayoutDashboard", admin: false },
  { href: "/veiculos?tipo=betoneira", label: "Betoneiras", icon: "Truck", admin: false },
  { href: "/veiculos?tipo=veiculo", label: "Caminhões", icon: "Truck", admin: false },
  { href: "/planos", label: "Planos preventivos", icon: "ClipboardList", admin: false },
  { href: "/ordens", label: "Ordens de manutenção", icon: "Wrench", admin: false },
  { href: "/problemas", label: "Problemas", icon: "AlertTriangle", admin: false },
  { href: "/historico", label: "Histórico", icon: "History", admin: false },
  { href: "/custos", label: "Custos", icon: "CircleDollarSign", admin: false },
  { href: "/calendario", label: "Calendário", icon: "Calendar", admin: false },
  { href: "/permissoes", label: "Permissões", icon: "ShieldCheck", admin: false },
  { href: "/configuracoes", label: "Configurações", icon: "Settings", admin: true },
  { href: "/usuarios", label: "Usuários", icon: "Users", admin: true },
  { href: "/auditoria", label: "Auditoria", icon: "ScrollText", admin: true },
] as const;
